### ISSUE TITLE
[功能请求]  可不可以加个打开闪照和备份与恢复

### ISSUE THREAD

**Issue by SnowPaper114514** [suzhelan/TimTool#11]
简单清晰的描述你所需要的功能：
打开闪照就顾名思义，闪照不会正常在10秒后消失，备份与恢复希望能备份小助手的那个独立的表情文件夹里面的表情和分类

**Comment by suzhelan** [comment]
闪照已列入功能列表，预计下个版本添加
备份目前只能自己手动备份一下，暂时不打算添加自动备份模式

**Comment by SnowPaper114514** [comment]
问题是我不会手动备份啊😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月14日(周六) 上午8:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [suzhelan/TimTool] [功能请求]  可不可以加个打开闪照和备份与恢复 (Issue #11)




 
闪照已列入功能列表，预计下个版本添加
 备份目前只能自己手动备份一下，暂时不打算添加自动备份模式

**Comment by suzhelan** [comment]
那等我加个手动导出导入的按钮吧
