### ISSUE TITLE
[BUG] +1位置和消息时间位置全部异常

### ISSUE THREAD

**Issue by My-Stars-Sky** [suzhelan/TimTool#15]
![IMG_20241220_001534.jpg](https://github.com/user-attachments/assets/343096d4-f557-40c0-92fa-e66cc1b9f748)

**Comment by suzhelan** [comment]
qq什么版本

**Comment by My-Stars-Sky** [comment]
> tim什么版本

4096到4098都这样

**Comment by My-Stars-Sky** [comment]
> 换个4097版本再试试，我测了4097和4098没问题

找到问题了QA和tim助手一起用导致的，取消QA后强行停止也不行，重新安装一遍就好了，我甚至能复现这个问题，可能是QA的Ci版本有点问题，QA更新到最新的Ci版就不会出现这个问题了
