### ISSUE TITLE
[BUG] 模块设置无法持久化保存

### ISSUE THREAD

**Issue by Lucas04-nhr** [suzhelan/TimTool#17]
TIM版本（无效的版本 或 带有最新版字样 将会被关闭）：QQNT 9.1.25

模块版本：1.8

清晰的描述你所遇到的问题（带上视频/图片/日志）难以排查或无效的反馈信息将会被关闭：在设置页面清除QQ缓存后模块设置将被重置。

**Comment by suzhelan** [comment]
https://github.com/suzhelan/TimTool/commit/8714b5a288fbff512ab6f0e2283c9b4c5facdf16
