### ISSUE TITLE
[功能请求]  自动勾选发送原图

### ISSUE THREAD

**Issue by 6ur9er** [suzhelan/TimTool#18]
简单清晰的描述你所需要的功能：
发送图片时自动勾选发送原图，包括半屏选择图片或是相册选择图片等情况

**Comment by HdShare** [comment]
TIM没有半屏选择图片吧
看起来只有 全屏选择+预览图片 那两个勾选原图框

**Comment by suzhelan** [comment]
> TIM没有半屏选择图片吧 看起来只有 全屏选择+预览图片 那两个勾选原图框

有的 
![Uploading Screenshot_2024-12-25-18-21-51-52_cb819d8fa60af39fdbc84f6c72b4cf1c.jpg…]()
