### ISSUE TITLE
每次存在更新时app闪退

### ISSUE THREAD

**Issue by xiaojie96528** [suzhelan/TimTool#2]
首先，只要更新到最新版就不会闪退了。问题不da。
但是目前此框架更新频繁，每天都会更新。所以其实也很烦人。
我打开tim时，只要存在有最新版，tim就必秒退。
已经好几个版本都是这样了。我从1.0开始用到1.2版本。
我怀疑是有请求最新版之类的代码，还是通知？每次触发到那就闪退？
手机是一加10pro   NE2210 Android 14 (34) arm64-v8a  已解锁root  
框架是LSPosed Zygisk 1.9.2（7024）

查看模块日志在循环，因为我重复点击重复闪退，日志如下:
[TIM小助手]环境初始化完成
Loading legacy module top.sacz.timtool from /data/app/~~XxXsadPQzsyy6pYpPj58JA==/top.sacz.timtool-LNv76_NTq6FIZIU9F8nfQQ==/base.apk
Loading  class top.sacz.timtool.hook.InjectHook
Loading legacy module top.sacz.timtool from /data/app/~~XxXsadPQzsyy6pYpPj58JA==/top.sacz.timtool-LNv76_NTq6FIZIU9F8nfQQ==/base.apk
Loading  class top.sacz.timtool.hook.InjectHook
[TIM小助手]环境初始化完成
Loading legacy module top.sacz.timtool from /data/app/~~XxXsadPQzsyy6pYpPj58JA==/top.sacz.timtool-LNv76_NTq6FIZIU9F8nfQQ==/base.apk
Loading  class top.sacz.timtool.hook.InjectHook
Loading legacy module top.sacz.timtool from /data/app/~~XxXsadPQzsyy6pYpPj58JA==/top.sacz.timtool-LNv76_NTq6FIZIU9F8nfQQ==/base.apk
Loading  class top.sacz.timtool.hook.InjectHook
[TIM小助手]环境初始化完成
Loading legacy module top.sacz.timtool from /data/app/~~XxXsadPQzsyy6pYpPj58JA==/top.sacz.timtool-LNv76_NTq6FIZIU9F8nfQQ==/base.apk
Loading  class top.sacz.timtool.hook.InjectHook
Loading legacy module top.sacz.timtool from /data/app/~~XxXsadPQzsyy6pYpPj58JA==/top.sacz.timtool-LNv76_NTq6FIZIU9F8nfQQ==/base.apk
Loading  class top.sacz.timtool.hook.InjectHook

**Comment by suzhelan** [comment]
没有发现明显日志，留一下lsp导出的.zip日志，发到tg群组或者suzhelan@gmail.com

**Comment by xiaojie96528** [comment]
[LSPosed_2024-12-18T11_03_39.865781.zip](https://github.com/user-attachments/files/18174239/LSPosed_2024-12-18T11_03_39.865781.zip)
今天又出现了闪退，我立即导出了log 。不知道什么原因 时间大概在2024-12-18 11:03

**Comment by xiaojie96528** [comment]
今天又出现了闪退，我立即导出了log，log已发到邮箱 。不知道什么原因 闪退时间大概在2024-12-18 11:03

**Comment by suzhelan** [comment]
close https://github.com/suzhelan/TimTool/commit/aa533a87ac8bc378a25a32580639f00ee29872d8
