### ISSUE TITLE
[功能请求]  将复读添加至消息长按菜单

### ISSUE THREAD

**Issue by Chen-hai-0721** [suzhelan/TimTool#21]
简单清晰的描述你所需要的功能：
就类似QA的复读那样添加至消息长按菜单，目前的方式有误触的可能

**Comment by Keeperorowner** [comment]
@suzhelan 多次框选文本的调整范围，会导致复读按钮重复生成![Screenshot_2025-01-07-22-31-03-35_cb819d8fa60af39fdbc84f6c72b4cf1c.jpg](https://github.com/user-attachments/assets/f6e6c37f-9fb2-4e21-9f6c-581de9c8ba7d)
