### ISSUE TITLE
[BUG] 深色模式未正确识别

### ISSUE THREAD

**Issue by Any1zz** [suzhelan/TimTool#24]
TIM版本：4.0.98

模块版本：2.0
![Screenshot_20241231-035408](https://github.com/user-attachments/assets/e4cfc781-847a-4246-a83a-8dca05cfa9ec)
![Screenshot_20241231-040026](https://github.com/user-attachments/assets/49736729-bf5d-4481-acf9-260181e069e3)

清晰的描述你所遇到的问题：
修改气泡圆角度设置里对于气泡颜色的修改无法正确识别深色模式，在tim里手动选择深色模式，气泡颜色仍显示常规模式下的颜色。
只有在tim里设置开启跟随系统后，再将系统切换到深色模式才能生效。

**Comment by suzhelan** [comment]
在预期情况中 无需反馈
